plugins: []
exclude:
  - src
  - node_modules
  - package.json
  - package-lock.json
  - eslint.config.js
  - vite.config.js
  - vercel.json
  - local-server.cjs
  - README.md
  - .gitignore
  - public
